### PR TITLE
Exit if upgrade have no new version?

### PR DESCRIPTION
**Pull request by ZeusF1**
With this its goes to  help_message, which is incorrect IMO

### CODE REVIEW

**Comment by srvrco** [comment]
That would mean you couldn't use -u in combination with other options though. 

I tend to use 
> checkssl -f ssl-domains -e 30 -r -u

which checks the domains in the file "ssl-domains" and will email me notification for any less than 30 days until renewal.  It will also upgrade if there is an upgrade available.    With your fix, such a command would never run anything.

**Comment by ZeusF1** [comment]
@srvrco 
True, then --silent would be an option or I just mute it output to /dev/null

**Comment by srvrco** [comment]
What are you trying to achieve / do ? 
The aim of the -u option was so that when added on a cron, along with the other commands, it maintains checkssl at the latest version.

**Comment by ZeusF1** [comment]
IMO -u  should be by default basically - 
if started - check for new version and do what asking.

Same as certbot do.
In my case I do:

/opt/tls/checkssl -u  && /opt/tls/certbot-auto -v
Just to keep things updated.

**Comment by srvrco** [comment]
I've added a slightly different update which should meet your requirement.

**Comment by ZeusF1** [comment]
Danke :)

**Pull request closed without merging**
